### ISSUE TITLE
Missing values in iterator bug

### ISSUE THREAD

**Issue by gregapompe** [racke/Template-Flute#11]
If you pass hash like this to iterator, "Status" and "Active" will also have class 'selected'. Some condition bug probably.

[
          {
            'label' => 'UID',
            'field' => 'uid'
          },
          {
            'class' => 'selected',
            'label' => 'Username',
            'field' => 'username'
          },
          {
            'label' => 'Status',
            'field' => 'status'
          },
          {
            'class' => undef,
            'label' => 'Active',
            'field' => 'active'
          },
]

**Comment by racke** [comment]
Added test through 5eac275 which proves that this problem doesn't occur any more.
