### ISSUE TITLE
problem dotted notation using 'field'

### ISSUE THREAD

**Issue by SysPete** [racke/Template-Flute#131]
with spec:
```
<value name="somename" field="errors.foo"/>
```
Then TF will happily use token 'foo' as replacement when it should only be using
   `$tokens->{errors}->{foo}`
or method 
   `$tokens->{errors}->foo`

See PR #130 for test which demonstrates this issue.

**Comment by racke** [comment]
Doesn't seem to be the case any longer. Added test for this situation: ec2628a.

**Comment by racke** [comment]
Fixed.
