### ISSUE TITLE
Add Markdown filter 

### ISSUE THREAD

**Issue by racke** [racke/Template-Flute#162]
We are using the following Template::Flute filter in the Perl Dancer Conference website:

https://github.com/interchange/Perl-Dancer-Conference/blob/master/lib/PerlDance/Filter/Markdown.pm

So in order to integrate that with Template::Flute, we need to do the following things:
- Change module name
- Write tests which are only running when prerequisites are satisfied
- Adjust POD to match other filters 
- Add to main POD

The existing currency filter can be used as example.

**Comment by SysPete** [comment]
We need to allow options to be passed through to HTML::Scrubber for allow, deny and rules. We could perhaps have '-allow/+allow' to remove/add options and 'allow' to replace? Rules will need to be handled slightly differently since it is a hash.

**Comment by racke** [comment]
Yes, that would be a good idea. But let me get it in just as-is before thinking about the options,
so I can use it in the [demo shop](https://github.com/interchange/Interchange6-Demo-Shop).

**Comment by racke** [comment]
Added through 8f9e7180132f0ea22c7255e32e7decb161641d3e.
