### ISSUE TITLE
Parse::RecDecent usage in Expression needs cache/precompile

### ISSUE THREAD

**Issue by SysPete** [racke/Template-Flute#81]
NYTprof data with a container inside a nested list so container value is rechecked 186 times:

Stmts	|Exclusive Time | Reports  | Source File
--------|-----------|-----------|--------------
208892	|3.22s	    |line	|Parse/RecDescent.pm (including 154 string evals)
46165	|2.03s	    |line	|XML/Twig.pm (including 22 string evals)
9	|1.01s	    |line	|DBIx/Class/Storage/DBI.pm
589249	|773ms	    |line	|HTML/Element.pm
209395	|324ms	|line	|HTML/TreeBuilder.pm
6231	|35.9ms	|line	|DBIx/Class/SQLMaker.pm
8	|28.8ms	|line	|Template/Flute.pm (including 3 string evals)
10	|27.0ms	|line	|DBIx/Class/ResultSet.pm

**Comment by racke** [comment]
Wondering if this should be solved quickly or taken care of by the rewrite.

**Comment by mrmaloof** [comment]
How about solved quickly? I'd like to use this in production soon.

**Comment by racke** [comment]
I suppose you are right ... rewrites take always longer than you fathomed. I'll look into this in the next few days.

**Comment by mrmaloof** [comment]
Cool! Thank you. YTB (you're the best).

**Comment by racke** [comment]
@SysPete, can you point me to a URL in Interchange6 demo shop which exposes this problem?

**Comment by racke** [comment]
At any rate, should be fixed by 63bf252.

**Comment by racke** [comment]
The disadvantage is that the cache is never purged, which could lead to big app processes if lots of templates are used.

Suggestions?

**Comment by SysPete** [comment]
@racke I put a lot of effort into demoshop pages to work around this so at the moment there are no pages where this is a real problem. Next target is twig.

**Comment by racke** [comment]
I used for product-listing-sidebar-left for testing, but it didn't use much containers (after editing it to use the container).

"twig" ?

**Comment by SysPete** [comment]
How about using Tie::CHI (or just CHI directly) for cache? Then at least rarely-used pages will expire from cache.

**Comment by SysPete** [comment]
@racke: by twig I mean the 2s spent in XML::Twig - another issue needed there.

**Comment by racke** [comment]
OK please create an issue - this would be much harder to tackle though.
