### ISSUE TITLE
Basic spec not passing date from DBIC object.

### ISSUE THREAD

**Issue by sbatschelet** [racke/Template-Flute#93]
basic Dancer/IC6 route
```
get '/test' => sub {
    my $tokens;
    my $order = shop_order(1);
    $tokens->{order} = $order;
    template '/email/order-receipt.html',$tokens,{layout => undef};
};
```

```
<html>
<head>
</head>
<body>
<font color=red"><span id="date"></span></font>
</body>
</html>
```

```
<specification>
<value name="date" id="date" field="order.order_date"/>
</specification>
```

**Comment by racke** [comment]
Fixed in release 0.0170.

**Comment by sbatschelet** [comment]
would this be related? 

request to POST /checkout crashed: DBIx::Class::InflateColumn::DateTime::catch {...} (): Error while inflating '2015-03-31T21:57:08' for order_date on Interchange6::Schema::Result::Order=HASH(0xdfe46d0): Invalid date format: 2015-03-31T21:57:08 at /home/sam/camp10/local/lib/perl5/Dancer/Template/TemplateFlute.pm line 505. at /home/sam/camp10/local/lib/perl5/Template/Flute.pm line 1427 in (eval 1046) l. 6

**Comment by racke** [comment]
Can you update to latest release and provide more details?

**Comment by racke** [comment]
Ok we found that this crash wasn't related.
